### ISSUE TITLE
Editing on mobile breaks the pitch accent graph

### ISSUE THREAD

**Issue by doctorhibert** [friedrich-de/Basic-Mining-Deck#2] opened 2023-05-05 00:42 UTC
If I click the edit button on mobile and save the card, even if I didn't actually change anything, the pitch accent graph disappears and is replaced by a massive empty space. This effect remains when the card is later seen on PC, though editing cards on PC produces no errors.

**Comment by friedrich-de** [comment] 2023-05-07 17:37
I'm afraid I can't reproduce this. Is this on AnkiDroid?
Do you see any change in the pitch accent field if you enable the HTML view?

**Comment by doctorhibert** [comment] 2023-05-10 22:22
Yes. It's on ankidroid. On PC, the "Graph" subsection of the card is actually empty, but it renders fine both in the preview and as a new card. On mobile, the graph section has all the code in it, and while it looks fine as a new card, if you click preview it's broken, and if you click ok after that it stays broken. 
The card on PC:
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/9555b5c3-ec80-4272-8fc7-d473f02034a1)
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/dadbeab1-b736-48ad-8ae1-b7cbe793b6be)
The graph code that only shows up on mobile:
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 100" style="display:inline-block;height:2em;">
    <defs>
        <g id="term-pitch-accent-graph-dot"><circle cx="0" cy="0" r="15" style="fill:#ffffff;stroke:#ffffff;stroke-width:5;" /></g>
        <g id="term-pitch-accent-graph-dot-downstep"><circle cx="0" cy="0" r="15" style="fill:none;stroke:#ffffff;stroke-width:5;" /><circle cx="0" cy="0" r="5" style="fill:none;stroke:#ffffff;stroke-width:5;" /></g>
        <g id="term-pitch-accent-graph-triangle"><path d="M0 13 L15 -13 L-15 -13 Z" style="fill:none;stroke:#ffffff;stroke-width:5;" /></g>
    </defs>
    <path style="fill:none;stroke:#ffffff;stroke-width:5;" d="M25 75L75 25L125 25L175 25"></path>
    <path style="fill:none;stroke:#ffffff;stroke-width:5;stroke-dasharray:5 5;" d="M175 25 L225 25"></path>
    <use href="#term-pitch-accent-graph-dot" x="25" y="75"></use>
    <use href="#term-pitch-accent-graph-dot" x="75" y="25"></use>
    <use href="#term-pitch-accent-graph-dot" x="125" y="25"></use>
    <use href="#term-pitch-accent-graph-dot" x="175" y="25"></use>
    <use href="#term-pitch-accent-graph-triangle" x="225" y="25"></use>
</svg>

How the card looks on mobile as a new card:
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/0fc40021-d3f6-4610-aa94-87a48906b0bf)
How it looks in the preview and any time afterwards if you press okay:
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/15fd800c-6d83-4fe9-b8b3-f4e705557f70)

I'm not entirely sure how to enable HTML view in ankidroid, but here's the code for the back of the card I can see on PC:
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/bba2c140-d606-4577-9798-c65264e620ca)
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/377dd612-7a78-438e-b005-d3d7bdee389c)

And the styling:
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/de619158-0a0f-4594-92e0-6b0102f4d824)
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/aeea5710-b8d1-40f9-b7d1-ad4e5b4bbee4)
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/e71c5ed0-9e02-4bb3-a72d-ab9938a2d492)


I have no idea if any of this is helping, but it's all I got.

**Comment by doctorhibert** [comment] 2023-05-10 22:24
I saw the code when I wrote the comment, but now that it's published it's invisible for some reason. I'll add the mobile code as an image in case you can't see it either.
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/bb5136db-b851-43b0-b44f-6671ae4cc515)
![image](https://github.com/friedrich-de/Basic-Mining-Deck/assets/46629336/8d67a359-fd6d-4a6a-83bd-bfb6880b59cb)

**Comment by doctorhibert** [comment] 2023-05-10 23:02
Hmm. I've been looking into it and I think it might be related to my handlebars file, which I think was leftover from when you still had to edit it for yomichan. I reset it and the new cards look fine for now, but it doesn't seem to have affected any of the old cards. Is there any way to fix this, or am I screwed?

**Comment by friedrich-de** [comment] 2023-05-16 16:49
> Hmm. I've been looking into it and I think it might be related to my handlebars file, which I think was leftover from when you still had to edit it for yomichan. I reset it and the new cards look fine for now, but it doesn't seem to have affected any of the old cards. Is there any way to fix this, or am I screwed?

Sorry I'm replying so slow, been kind of busy lately.

If the handlebars caused the issue there isn't a way to easily fix it. You'd have to edit the cards with a script or something but that's not trivial. But at least it's fixed now with clean reset handlebars, right?

**Comment by doctorhibert** [comment] 2023-05-16 18:51
Yeah, it's fixed now, I'll just edit the old cards on PC. It might be a good idea to add a step to the readme about resetting the handlebars before installing for dumb people like me.

**Comment by friedrich-de** [comment] 2023-07-07 12:49
Added a note to the README.md

**Closed as completed by friedrich-de** 2023-07-07 12:49 UTC
